# 監視対象
# jsonにするとコメントが書けないので、pythonスクリプトとする。importで手軽に読み込めるし。
SEARCH_WORDS = [
    '機械学習',
    'machine+learning',
    'ディープラーニング',
    '深層学習',
    'deep+learning',
    'python',
    'tensorflow',
    'chainer',
    'pytoach'
    '自然言語',
    'NLP',
    '異常検知',
    'スパースモデリング',
    '可視化',
    'ビジュアライ',  # ビジュアライズ、ビジュアライゼーションどちらもヒットする
    'kaggle',
    '人工知能',
    'データサイエン',  # データサイエンス、データサイエンティストどちらもヒットする
    'MCMC',
    'ベイズ',
    'テキストマイニング',
    # 'クラウド',
    'Azure',
    'GCP',
    'AWS',
    # 'google+cloud',
    'nosql',
    # 'mysql',  # sql入門とかでヒットが多すぎる
    'postgresql',
    'ビッグデータ',
    'spark',
    'ハッカソン',
    '統計',
    '数学',
    'docker',
    '自動化',
    'CI',
    'DevOps',
    'ChatOps',
    'UX',
    # 'ブロックチェーン',
    # 'blockchain',
    # 'fintech',       # ぼんやりとしたものが多いので対象外
    # 'フィンテック',    # ぼんやりとしたものが多いので対象外
    'slack',
    # 'Ruby+on+Rails',
    # 'CakePHP',
    # 'PHP',
    'node.js',
    # 'リーンスタートアップ',
    'アジャイル',
    'スクラム',
    '効率化',
    'テレワーク',
    'ワークスタイル',
    '人事',
    '労務',
    # 'RPA',
    '働き方改革'
]
